#!/bin/bash
set -euo pipefail

# -----------------------------
# Config
# -----------------------------
APP_NAME="myapp"
TOMCAT_SERVICE="tomcat"

# These match the tomcat-mysql image (build-vm-images):
#   - Tomcat installed under /opt/tomcat, WARs dropped into its default appBase.
#   - Config externalized to /etc/apps and exposed to the app as -Dconfig.dir.
# See scripts/ubuntu/{install-tomcat.sh,setenv.sh,tomcat.service}.
TOMCAT_WEBAPPS="/opt/tomcat/webapps"
CONFIG_DIR="/etc/apps"
TOMCAT_USER="tomcat"
TOMCAT_GROUP="tomcat"

# Option A: Google Cloud Storage WAR
GCS_WAR_URI="gs://my-bucket/releases/myapp.war"

# Option B: Artifact Registry generic repo
# Example:
# ARTIFACT_WAR_URI="https://LOCATION-generic.pkg.dev/PROJECT_ID/REPO_NAME/myapp/myapp.war"
ARTIFACT_WAR_URI=""

MYSQL_ROOT_USER="root"
MYSQL_ROOT_PASSWORD="root_password_here"

APP_DB="myappdb"
APP_DB_USER="myappuser"
APP_DB_PASSWORD="change_this_password"

TMP_WAR="/tmp/${APP_NAME}.war"

# -----------------------------
# Download WAR
# -----------------------------
echo "Downloading WAR..."

if [[ -n "$ARTIFACT_WAR_URI" ]]; then
  ACCESS_TOKEN="$(gcloud auth print-access-token)"
  curl -fL \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
    -o "$TMP_WAR" \
    "$ARTIFACT_WAR_URI"
else
  gsutil cp "$GCS_WAR_URI" "$TMP_WAR"
fi

# -----------------------------
# Create MySQL DB and user
# -----------------------------
echo "Creating MySQL database and user..."

mysql -u"${MYSQL_ROOT_USER}" -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${APP_DB}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${APP_DB_USER}'@'localhost'
  IDENTIFIED BY '${APP_DB_PASSWORD}';

ALTER USER '${APP_DB_USER}'@'localhost'
  IDENTIFIED BY '${APP_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${APP_DB}\`.* TO '${APP_DB_USER}'@'localhost';

FLUSH PRIVILEGES;
SQL

# -----------------------------
# Write application properties BEFORE deploying the WAR
# -----------------------------
# The image exports CONFIG_DIR=/etc/apps and passes -Dconfig.dir=/etc/apps to the
# JVM (see setenv.sh). The app reads its config from there, so the properties file
# must exist before the WAR starts up for the first time.
echo "Writing application properties to ${CONFIG_DIR}/${APP_NAME}.properties..."

install -d -o "$TOMCAT_USER" -g "$TOMCAT_GROUP" -m 750 "$CONFIG_DIR"

PROPS_FILE="${CONFIG_DIR}/${APP_NAME}.properties"
umask 077
cat > "$PROPS_FILE" <<PROPS
# Generated by assess-server.sh on $(date --iso-8601=seconds)
spring.datasource.url=jdbc:mysql://localhost:3306/${APP_DB}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${APP_DB_USER}
spring.datasource.password=${APP_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
PROPS
umask 022

chown "$TOMCAT_USER":"$TOMCAT_GROUP" "$PROPS_FILE"
chmod 640 "$PROPS_FILE"

# -----------------------------
# Deploy WAR to Tomcat (hot deploy, no service restart)
# -----------------------------
# Tomcat's default host has autoDeploy="true" and unpackWARs="true", so dropping a
# WAR into the appBase makes Tomcat explode and deploy it live — no restart needed.
# Remove the previous exploded dir and WAR first so the new one is picked up as a
# fresh deploy.
echo "Removing old deployment..."
rm -rf "${TOMCAT_WEBAPPS:?}/${APP_NAME}"
rm -f "${TOMCAT_WEBAPPS}/${APP_NAME}.war"

echo "Deploying new WAR..."
# Copy to a temp name in the same dir, then rename, so Tomcat's watcher never sees
# a partially-written WAR.
cp "$TMP_WAR" "${TOMCAT_WEBAPPS}/.${APP_NAME}.war.tmp"
chown "$TOMCAT_USER":"$TOMCAT_GROUP" "${TOMCAT_WEBAPPS}/.${APP_NAME}.war.tmp"
mv "${TOMCAT_WEBAPPS}/.${APP_NAME}.war.tmp" "${TOMCAT_WEBAPPS}/${APP_NAME}.war"

echo "Waiting for Tomcat to explode and deploy the WAR..."
for _ in $(seq 1 60); do
  if [[ -d "${TOMCAT_WEBAPPS}/${APP_NAME}" ]]; then
    echo "WAR exploded to ${TOMCAT_WEBAPPS}/${APP_NAME}"
    break
  fi
  sleep 2
done

if [[ ! -d "${TOMCAT_WEBAPPS}/${APP_NAME}" ]]; then
  echo "WARNING: WAR not exploded after timeout. Check ${TOMCAT_SERVICE} logs." >&2
fi

echo "Deployment complete."
echo "App should be available at: /${APP_NAME}"
