#!/bin/bash
set -euo pipefail

# -----------------------------------------------------------------------------
# Container variant of deploy-assess.sh.
#
# This is the DOCKER counterpart of vm/deploy-assess.sh. It is intentionally a
# separate copy, not a shared script (see build-docs / the split rationale):
# the VM and container runtimes differ in ways that don't reduce to a flag.
#
# Differences from vm/deploy-assess.sh:
#   - No `tomcat` service user. In the container image Tomcat runs as the
#     container's main process (PID 1, as root); there is no separate 'tomcat'
#     user/group, so every `chown tomcat:tomcat` / `install -o tomcat` from the
#     VM script is dropped (they would fail with "invalid user: tomcat" and, under
#     `set -e`, abort the deploy and kill the container).
#   - Tomcat is already running (started by tomcat-entrypoint.sh AFTER this script
#     returns) — so this is a pure deploy step: drop the WAR + write config, then
#     return. There is no systemd service to coordinate with.
#   - Invoked by docker-startup.sh as `<APP_NAME>.sh APP_NAME APP_ENV`; it returns,
#     and the entrypoint then execs `catalina.sh run` to serve. So the WAR does
#     NOT need to hot-deploy into a live Tomcat here — Tomcat starts fresh right
#     after and picks up whatever is in webapps.
# -----------------------------------------------------------------------------

# -----------------------------
# Config
# -----------------------------
# APP_NAME / APP_ENV arrive as positional args from docker-startup.sh; fall back to
# the previous hardcoded default if run standalone.
APP_NAME="${1:-myapp}"
APP_ENV="${2:-development}"

# Matches the tomcat docker image (build-docker/tomcat-dockerfile):
#   - Tomcat installed under /opt/tomcat, WARs dropped into its default appBase.
#   - Config externalized to /etc/apps (setenv.sh passes -Dconfig.dir=/etc/apps).
TOMCAT_WEBAPPS="/opt/tomcat/webapps"
CONFIG_DIR="/etc/apps"

# Option A: Google Cloud Storage WAR
GCS_WAR_URI="gs://my-bucket/releases/myapp.war"

# Option B: Artifact Registry generic repo
ARTIFACT_WAR_URI=""

MYSQL_ROOT_USER="root"
MYSQL_ROOT_PASSWORD="root_password_here"

APP_DB="myappdb"
APP_DB_USER="myappuser"
APP_DB_PASSWORD="change_this_password"

TMP_WAR="/tmp/${APP_NAME}.war"

# -----------------------------
# Download WAR
# -----------------------------
echo "Downloading WAR for ${APP_NAME} (${APP_ENV})..."

if [[ -n "$ARTIFACT_WAR_URI" ]]; then
  ACCESS_TOKEN="$(gcloud auth print-access-token)"
  curl -fL \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
    -o "$TMP_WAR" \
    "$ARTIFACT_WAR_URI"
else
  gsutil cp "$GCS_WAR_URI" "$TMP_WAR"
fi

# -----------------------------
# Write application properties BEFORE deploying the WAR
# -----------------------------
# setenv.sh passes -Dconfig.dir=/etc/apps to the JVM; the app reads its config
# from there, so the properties file must exist before Tomcat starts.
echo "Writing application properties to ${CONFIG_DIR}/${APP_NAME}.properties..."

install -d -m 750 "$CONFIG_DIR"

PROPS_FILE="${CONFIG_DIR}/${APP_NAME}.properties"
umask 077
cat > "$PROPS_FILE" <<PROPS
# Generated by docker/deploy-assess.sh on $(date --iso-8601=seconds)
spring.datasource.url=jdbc:mysql://localhost:3306/${APP_DB}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${APP_DB_USER}
spring.datasource.password=${APP_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
PROPS
umask 022
chmod 640 "$PROPS_FILE"

# -----------------------------
# Deploy WAR to Tomcat's appBase
# -----------------------------
# Tomcat is not running yet in this container (the entrypoint execs
# `catalina.sh run` AFTER this script returns), so this is a plain file drop —
# no hot-deploy race, no service restart. Remove any prior deployment first.
echo "Removing old deployment..."
rm -rf "${TOMCAT_WEBAPPS:?}/${APP_NAME}"
rm -f "${TOMCAT_WEBAPPS}/${APP_NAME}.war"

echo "Deploying new WAR..."
cp "$TMP_WAR" "${TOMCAT_WEBAPPS}/${APP_NAME}.war"

echo "Deployment staged. Tomcat will explode and serve /${APP_NAME} on startup."
